stages:
  prepare:
    cmd: source src/prepare.sh
    deps:
    - src/prepare.sh
    outs:
    - raw-data
  transform:
    cmd: python src/transform.py
    deps:
    - src/transform.py
    - raw-data
    outs:
    - transformed_data
    - index_files
  train:
    cmd: python src/train.py
    deps:
    - src/train.py
    - transformed_data
    outs:
    - models
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - models
    - src/evaluate.py
metrics:
- eval/metrics.json
plots:
- eval/plots/metrics:
    x: step
