stages:
  prepare:
    cmd: source src/prepare.sh
    deps:
    - src/prepare.sh
    outs:
    - raw-data
  visualise:
    cmd: python src/visualise.py
    deps:
    - raw-data
    - src/visualise.py
    outs:
    - visualise
  transform:
    cmd: python src/transform.py
    params:
    - transform.test_size
    - transform.seq_length
    - transform.n_mels
    - transform.stride
    deps:
    - raw-data
    outs:
    - sequences:
        cache: false
    - dict
  train:
    cmd: python src/train.py
    params:
    - train.model_name
    - train.epochs
    - train.batch_size
    deps:
    - src/train.py
    - sequences
    outs:
    - models
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - models
    - src/evaluate.py
    outs:
    - eval/
metrics:
- eval/metrics.json
plots:
- visualise/plots/images
- eval/plots/metrics:
    x: step
- eval/plots/images
params:
- dict/params.yaml
