stages:
  prepare:
    cmd: source src/prepare.sh
    deps:
    - src/prepare.sh
    outs:
    - raw-data
  transform:
    cmd: python src/transform.py
    params:
    - transform.test_size
    - transform.seq_length
    - transform.n_mels
    - transform.stride
    deps:
    - src/transform.py
    - raw-data
    outs:
    - transformed_data
    - sequences
    - index_files
    - dict
  train:
    cmd: python src/train.py
    params:
    - train.model_name
    deps:
    - src/train.py
    - transformed_data
    outs:
    - models
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - models
    - src/evaluate.py
    outs:
    - eval/
metrics:
- eval/metrics.json
plots:
- eval/plots/metrics:
    x: step
- eval/plots/images
params:
- dict/params.yaml
